# job_gpu_keepalive.sub
universe              = vanilla
executable            = /bin/sleep
arguments             = "864000"
#getenv                = True
when_to_transfer_output = ON_EXIT_OR_EVICT
should_transfer_files = YES
transfer_input_files = exp_refactor2.py, wrapper.sh, install_requirements.sh, updated_transformer.py, hardcoded_transformer.py

request_cpus          = 32
request_memory        = 120G
request_gpus          = 4

# IMPORTANT: no HasSSHToJob here; your pool doesn't advertise it
requirements          = (GPUs_Capability >= 7.0) && (GPUs_GlobalMemoryMb >= 50000)

log                   = parking.log
output                = parking.out
error                 = parking.err
queue 1
