# job_gpu_keepalive.sub
universe              = vanilla
executable            = /bin/sleep
arguments             = "8640000"
#getenv                = True
when_to_transfer_output = ON_EXIT_OR_EVICT
should_transfer_files = YES
#when_to_transfer_output = ON_EXIT
transfer_output_files = summary*
transfer_input_files = wrapper.sh

request_cpus          = 64
request_memory        = 240G
request_gpus          = 8

# IMPORTANT: no HasSSHToJob here; your pool doesn't advertise it
requirements          = (GPUs_Capability >= 7) && (GPUs_GlobalMemoryMb >= 50000)

log                   = parking.log
output                = parking.out
error                 = parking.err
queue 1
